<!-- app/views/index.phtml -->
<html>
<head>
    <title>Example</title>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>

<div class="container">
    <form class="form-signin text-center" method="post" action="/">
        <h1 class="h3 mb-3 font-weight-normal">Авторизация</h1>
        <div class="form-group">
            <label for="login" class="sr-only">Логин</label>
            <input
                type="text"
                id="login"
                name="login"
                class="form-control"
                placeholder="Логин"
                required
                autofocus
            >
        </div>

        <div class="form-group">
            <label for="inputPassword" class="sr-only">Пароль</label>
            <input
                type="password"
                name="password"
                id="inputPassword"
                class="form-control"
                placeholder="Пароль"
                required
            >
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Авторизоваться</button>
    </form>
</div>

</body>
</html>